name: Run Coverage on PR
on: pull-request

jobs:
  build-and-run-coverage:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Run tests and coverage
        run: npm run coverage

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
